import {
  type PatientRequest,
  RequestStatus,
  type ToolbarButton,
} from "./types";
import {
  EditCalendarOutlined as EditCalendarOutlinedIcon,
  TollOutlined as TollOutlinedIcon,
  Pause as PauseIcon,
  ForwardToInboxOutlined as ForwardToInboxOutlinedIcon,
  AllInclusiveOutlined as AllInclusiveOutlinedIcon,
  DoDisturbOutlined as DoDisturbOutlinedIcon,
} from "@mui/icons-material";

export const mockPatientRequests: PatientRequest[] = [
  {
    patientId: "318356985",
    patientName: "משה כהן",
    genericMedication: "ASPIRIN CARDIO",
    openRequestDate: "11.5.25",
    catoDosage: "60 mg",
    approvedDosage: "60 mg",
    numOfTreatments: 10,
    drugApprovalExpirationDate: "11.5.25",
    doctorInCharge: "רוית גבע",
    coordinatingNurse: "אחות רותי",
    fundingFactor: "חמלה",
    updatesStatusDate: "11.5.25",
    requestStatus: RequestStatus.InProgress,
  },
  {
    patientId: "318346985",
    patientName: "יהודה כהן",
    genericMedication: "ATROVATSTAN",
    openRequestDate: "11.5.25",
    catoDosage: "60 mg",
    approvedDosage: "60 mg",
    numOfTreatments: 2,
    drugApprovalExpirationDate: "11.5.25",
    doctorInCharge: "רוית גבע",
    coordinatingNurse: "אחות רותי",
    fundingFactor: "מכבי",
    updatesStatusDate: "11.5.25",
    requestStatus: RequestStatus.Declined,
  },
  {
    patientId: "318336985",
    patientName: "ליאור כהן",
    genericMedication: "ALDACTONE",
    openRequestDate: "11.5.25",
    catoDosage: "60 mg",
    approvedDosage: "60 mg",
    numOfTreatments: 6,
    drugApprovalExpirationDate: "11.5.25",
    doctorInCharge: "רוית גבע",
    coordinatingNurse: "אחות רותי",
    fundingFactor: "ביטוח בסיסי",
    updatesStatusDate: "11.5.25",
    requestStatus: RequestStatus.Accepted,
  },
  {
    patientId: "318326985",
    patientName: "יעקב יעקבי",
    genericMedication: "ASPIRIN CARDIO",
    openRequestDate: "11.5.25",
    approvedDosage: "100 mg",
    updatedInventory: 35.0,
    drugApprovalExpirationDate: "11.5.25",
    fundingFactor: "כללית",
    updatesStatusDate: "1.4.25",
    requestStatus: RequestStatus.OnHold,
  },
];

export const toolbarButtons: ToolbarButton[] = [
  { label: "הארכת תוקף - 15", icon: EditCalendarOutlinedIcon, color: "green" },
  { label: "שינוי מינון - 15", icon: TollOutlinedIcon, color: "purple" },
  { label: "מושהה - 15", icon: PauseIcon, color: "yellow" },
  { label: "נדרש מידע - 120", icon: ForwardToInboxOutlinedIcon, color: "grey" },
  { label: "מסתיים - 120", icon: AllInclusiveOutlinedIcon, color: "warning" },
  { label: "נדחתה - 3", icon: DoDisturbOutlinedIcon, color: "error" },
];
